" default globals vim configuration
set autoindent
set expandtab
set number
set ruler
set undofile
set undodir     =~/.vim/undo/
set background  =dark
set history     =500
set shiftwidth  =2
set softtabstop =2
set tabstop     =2
syntax on

" Allow netrw to remove non-empty local directories
let g:netrw_localrmdir = 'rm -r'

" autosave remote sshfs on tmp local
autocmd BufWritePost ~/prod-tmp/* :w! ~/tmp/prod/<afile>
autocmd BufWritePost ~/stag-tmp/* :w! ~/tmp/stag/<afile>

" auto read .vim/ftplugin with filetype
filetype plugin on
execute pathogen#infect()

" <C-k> open right panel with functions & contants
let g:Tlist_Ctags_Cmd   = "/usr/bin/ctags "
let g:Tlist_Auto_Update = 1
let g:Tlist_Sort_Type   = "name"
nnoremap <C-k> :Tlist<CR><C-w><C-h>
